apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mbcas-workloads
  namespace: vpa-mbcas-test
  labels:
    app: mbcas-test
spec:
  selector:
    matchLabels:
      test: mbcas
  endpoints:
  - port: http
    path: /metrics
    interval: 5s
