apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- service-a-overprovisioned.yaml
- service-b-underprovisioned.yaml
- service-c-bursty.yaml
- service-d-wellconfigured.yaml
