apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: gateway-vpa
  namespace: evaluation
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: gateway
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: worker-a-vpa
  namespace: evaluation
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: worker-a
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: worker-b-vpa
  namespace: evaluation
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: worker-b
  updatePolicy:
    updateMode: "Auto"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: noise-vpa
  namespace: evaluation
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: noise
  updatePolicy:
    updateMode: "Auto"
